<script lang="ts">
  import LoadingDots from "../UI/LoadingDots.svelte";
  import GeneratedImage from "../UI/GeneratedImage.svelte";

  import { AppState } from '$lib/stores/appv2.svelte';
  import { identifyPlaceholders, prepareGeneratingPlaceholder, processDependentValues, processPlaceholders } from '$lib/utils/prompts.svelte';

  // Props
  export let title: string;

  // Widget Details
  let widgetIndex: number = AppState.getWidgetByTitle(title).index || -1;
  let prompt: string | undefined = $AppState.widgets[widgetIndex].imageDescription + "";
  let placeholderText = prepareGeneratingPlaceholder(prompt || "");

  // Dependent Widget Details
  const dependentWidgets: string[] = identifyPlaceholders(prompt);
  let dependentValues: DependentValues[];

  // Widget Visual Elements
  let loadingStatus: boolean = false;
  let output: string = "";

  // Trigger Generation
  $: {
    const rememberValues = dependentValues;
    let valuesValid: boolean = true;
    let valuesChanged: boolean;

    dependentValues = processDependentValues(dependentWidgets, $AppState);

    dependentValues.forEach((w) => {
      if (typeof w.value == "undefined") {
        valuesValid = false;
      }
    });

    valuesChanged = !(JSON.stringify(dependentValues) === JSON.stringify(rememberValues));
    
    if (valuesValid && valuesChanged) {
      callBedrock();
    }
  }

  // Generation Function
  async function callBedrock(): Promise<void> {
    console.log(`<WidgetImageGeneration:${title}> callBedrock()`);
    
    if (typeof prompt == "undefined") {
      // Unhandled - Shouldn't happen with well-formed definition files
      throw "Prompt not found";
    }

    loadingStatus = true;
    try {
      let currentPrompt: PromptProcessed = processPlaceholders(prompt,$AppState);
      console.debug(currentPrompt);
      
      const resImg = await fetch('/api/call-bedrock', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ 
          model: "bedrock-stable-diffusion-xl",
          prompt: currentPrompt.prompt
        })
      });

      if (resImg.ok) {
        const dataImg = await resImg.json();
        output = dataImg.response;
        $AppState.widgets[widgetIndex].value = output;

        console.debug({title: title, originalPrompt: prompt, newPrompt: currentPrompt, response: "image"});
      } else {
        console.error(`Error: ${resImg}`);
      }
    }
    finally {
      loadingStatus = false;
    }
  }
</script>

<div class="party-widget-ai">
  <div class="party-widget-header">
      <label for="output">{title}</label>
      <LoadingDots loadState={loadingStatus} />
  </div>
  <div class="party-widget-contents-image">
      {#if output}
        <GeneratedImage base64Image={output} alt="Generated by Bedrock" />
      {:else}
        <span class="party-widget-placeholder">{@html placeholderText}</span>
        <br />
      {/if}          
  </div>
</div>